### ISSUE TITLE
Cleanup error messages

### ISSUE THREAD

**Issue by Spl3en** [rhizomeicx/marvin#1]
https://github.com/rhizomeicx/marvin/blob/a5fe2ba3e31c5fa49fc88f99517661314be6e626/Marvin/Marvin-Ubuntu/Program.cs#L29

https://github.com/rhizomeicx/marvin/blob/a5fe2ba3e31c5fa49fc88f99517661314be6e626/Marvin/Marvin-Ubuntu/Program.cs#L48

May we generate more descriptive error messages ? These errors are confusing

**Comment by Firefight-Rhizome** [comment]
It's on my list

**Comment by Firefight-Rhizome** [comment]
resolving RR: https://github.com/rhizomeicx/marvin/pull/3
